from PyQt5 import QtCore, QtWidgets, QtChart

class Ui_MainTab(object):
    def setupUi(self, MainTab):
        MainTab.setObjectName("MainTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainTab)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")

        self.groupPanTilt = QtWidgets.QGroupBox(MainTab)
        self.groupPanTilt.setObjectName("groupPanTilt")
        self.layoutPanTilt = QtWidgets.QVBoxLayout(self.groupPanTilt)
        self.layoutPanTilt.setObjectName("layoutPanTilt")

        self.groupMove = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupMove.setObjectName("groupMove")
        self.gridMove = QtWidgets.QGridLayout(self.groupMove)
        self.gridMove.setObjectName("gridMove")
        self.btnPanLeft = QtWidgets.QPushButton(self.groupMove)
        self.btnPanLeft.setObjectName("btnPanLeft")
        self.gridMove.addWidget(self.btnPanLeft, 1, 0, 1, 1)
        self.btnPanStop = QtWidgets.QPushButton(self.groupMove)
        self.btnPanStop.setObjectName("btnPanStop")
        self.gridMove.addWidget(self.btnPanStop, 1, 1, 1, 1)
        self.btnPanRight = QtWidgets.QPushButton(self.groupMove)
        self.btnPanRight.setObjectName("btnPanRight")
        self.gridMove.addWidget(self.btnPanRight, 1, 2, 1, 1)
        self.btnTiltUp = QtWidgets.QPushButton(self.groupMove)
        self.btnTiltUp.setObjectName("btnTiltUp")
        self.gridMove.addWidget(self.btnTiltUp, 0, 1, 1, 1)
        self.btnTiltDown = QtWidgets.QPushButton(self.groupMove)
        self.btnTiltDown.setObjectName("btnTiltDown")
        self.gridMove.addWidget(self.btnTiltDown, 2, 1, 1, 1)
        self.checkMoveStop = QtWidgets.QCheckBox(self.groupMove)
        self.checkMoveStop.setObjectName("checkMoveStop")
        self.gridMove.addWidget(self.checkMoveStop, 0, 3, 1, 2)
        self.btnStopAt = QtWidgets.QPushButton(self.groupMove)
        self.btnStopAt.setObjectName("btnStopAt")
        self.gridMove.addWidget(self.btnStopAt, 1, 4, 1, 1)
        self.editStopAt = QtWidgets.QLineEdit(self.groupMove)
        self.editStopAt.setObjectName("editStopAt")
        self.gridMove.addWidget(self.editStopAt, 2, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupMove)

        self.groupAbsolute = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupAbsolute.setObjectName("groupAbsolute")
        self.gridAbsolute = QtWidgets.QGridLayout(self.groupAbsolute)
        self.gridAbsolute.setObjectName("gridAbsolute")
        self.btnABS = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABS.setObjectName("btnABS")
        self.gridAbsolute.addWidget(self.btnABS, 0, 0, 1, 1)
        self.editABSPos = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSPos.setObjectName("editABSPos")
        self.gridAbsolute.addWidget(self.editABSPos, 0, 1, 1, 1)
        self.btnABS2 = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABS2.setObjectName("btnABS2")
        self.gridAbsolute.addWidget(self.btnABS2, 1, 0, 1, 1)
        self.editABS2Pos = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABS2Pos.setObjectName("editABS2Pos")
        self.gridAbsolute.addWidget(self.editABS2Pos, 1, 1, 1, 1)
        self.btnABSAngle = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngle.setObjectName("btnABSAngle")
        self.gridAbsolute.addWidget(self.btnABSAngle, 2, 0, 1, 1)
        self.editABSAngle = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSAngle.setObjectName("editABSAngle")
        self.gridAbsolute.addWidget(self.editABSAngle, 2, 1, 1, 1)
        self.btnABSAngle2 = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngle2.setObjectName("btnABSAngle2")
        self.gridAbsolute.addWidget(self.btnABSAngle2, 3, 0, 1, 1)
        self.editABSAngle2 = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSAngle2.setObjectName("editABSAngle2")
        self.gridAbsolute.addWidget(self.editABSAngle2, 3, 1, 1, 1)
        self.btnABSStop = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSStop.setObjectName("btnABSStop")
        self.gridAbsolute.addWidget(self.btnABSStop, 0, 2, 1, 1)

        self.groupPanType = QtWidgets.QGroupBox(self.groupAbsolute)
        self.groupPanType.setObjectName("groupPanType")
        self.layoutPanType = QtWidgets.QVBoxLayout(self.groupPanType)
        self.layoutPanType.setObjectName("layoutPanType")
        self.btnPanType = QtWidgets.QPushButton(self.groupPanType)
        self.btnPanType.setObjectName("btnPanType")
        self.layoutPanType.addWidget(self.btnPanType)
        self.comboPanMethod = QtWidgets.QComboBox(self.groupPanType)
        self.comboPanMethod.setObjectName("comboPanMethod")
        self.comboPanMethod.addItems(["Shorter Path", "Forced CW", "Forced CCW"])
        self.layoutPanType.addWidget(self.comboPanMethod)
        self.gridAbsolute.addWidget(self.groupPanType, 1, 2, 2, 1)

        self.btnABSAngleStop = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngleStop.setObjectName("btnABSAngleStop")
        self.gridAbsolute.addWidget(self.btnABSAngleStop, 3, 2, 1, 1)

        self.layoutPanTilt.addWidget(self.groupAbsolute)

        self.groupRelative = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupRelative.setObjectName("groupRelative")
        self.gridRelative = QtWidgets.QGridLayout(self.groupRelative)
        self.gridRelative.setObjectName("gridRelative")
        self.btnRelUp = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelUp.setObjectName("btnRelUp")
        self.gridRelative.addWidget(self.btnRelUp, 0, 1, 1, 1)
        self.btnRelLeft = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelLeft.setObjectName("btnRelLeft")
        self.gridRelative.addWidget(self.btnRelLeft, 1, 0, 1, 1)
        self.btnRelStop = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelStop.setObjectName("btnRelStop")
        self.gridRelative.addWidget(self.btnRelStop, 1, 1, 1, 1)
        self.btnRelRight = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelRight.setObjectName("btnRelRight")
        self.gridRelative.addWidget(self.btnRelRight, 1, 2, 1, 1)
        self.btnRelDown = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelDown.setObjectName("btnRelDown")
        self.gridRelative.addWidget(self.btnRelDown, 2, 1, 1, 1)
        self.labelRelStep = QtWidgets.QLabel(self.groupRelative)
        self.labelRelStep.setObjectName("labelRelStep")
        self.gridRelative.addWidget(self.labelRelStep, 1, 3, 1, 1)
        self.editRelStep = QtWidgets.QLineEdit(self.groupRelative)
        self.editRelStep.setObjectName("editRelStep")
        self.gridRelative.addWidget(self.editRelStep, 1, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupRelative)

        self.groupStall = QtWidgets.QGroupBox(MainTab)
        self.groupStall.setObjectName("groupStall")
        self.layoutStall = QtWidgets.QHBoxLayout(self.groupStall)
        self.layoutStall.setObjectName("layoutStall")
        self.btnStallCaliOn = QtWidgets.QPushButton(self.groupStall)
        self.btnStallCaliOn.setObjectName("btnStallCaliOn")
        self.layoutStall.addWidget(self.btnStallCaliOn)
        self.btnStallCaliOff = QtWidgets.QPushButton(self.groupStall)
        self.btnStallCaliOff.setObjectName("btnStallCaliOff")
        self.layoutStall.addWidget(self.btnStallCaliOff)

        # container for motor controls placed to the right of pan/tilt group
        self.layoutMotorCtrl = QtWidgets.QVBoxLayout()
        self.layoutMotorCtrl.setObjectName("layoutMotorCtrl")

        # Speed Control group
        self.groupSpeedControl = QtWidgets.QGroupBox(MainTab)
        self.groupSpeedControl.setObjectName("groupSpeedControl")
        self.layoutSpeedControl = QtWidgets.QVBoxLayout(self.groupSpeedControl)
        self.layoutSpeedControl.setObjectName("layoutSpeedControl")

        self.groupSpeedLevel = QtWidgets.QGroupBox(self.groupSpeedControl)
        self.groupSpeedLevel.setObjectName("groupSpeedLevel")
        self.layoutSpeedLevel = QtWidgets.QHBoxLayout(self.groupSpeedLevel)
        self.layoutSpeedLevel.setObjectName("layoutSpeedLevel")
        self.labelSpeedLevel = QtWidgets.QLabel(self.groupSpeedLevel)
        self.labelSpeedLevel.setObjectName("labelSpeedLevel")
        self.layoutSpeedLevel.addWidget(self.labelSpeedLevel)
        self.editSpeedLevel = QtWidgets.QLineEdit(self.groupSpeedLevel)
        self.editSpeedLevel.setObjectName("editSpeedLevel")
        self.layoutSpeedLevel.addWidget(self.editSpeedLevel)
        self.labelSpeedPPS = QtWidgets.QLabel(self.groupSpeedLevel)
        self.labelSpeedPPS.setObjectName("labelSpeedPPS")
        self.layoutSpeedLevel.addWidget(self.labelSpeedPPS)
        self.editSpeedInPPS = QtWidgets.QLineEdit(self.groupSpeedLevel)
        self.editSpeedInPPS.setObjectName("editSpeedInPPS")
        self.editSpeedInPPS.setReadOnly(True)
        self.layoutSpeedLevel.addWidget(self.editSpeedInPPS)
        self.layoutSpeedControl.addWidget(self.groupSpeedLevel)

        self.groupSpeedZoom = QtWidgets.QGroupBox(self.groupSpeedControl)
        self.groupSpeedZoom.setObjectName("groupSpeedZoom")
        self.layoutSpeedZoom = QtWidgets.QHBoxLayout(self.groupSpeedZoom)
        self.layoutSpeedZoom.setObjectName("layoutSpeedZoom")
        self.btnGetSpeedByZoomRatio = QtWidgets.QPushButton(self.groupSpeedZoom)
        self.btnGetSpeedByZoomRatio.setObjectName("btnGetSpeedByZoomRatio")
        self.layoutSpeedZoom.addWidget(self.btnGetSpeedByZoomRatio)
        self.btnSpeedByZoomOn = QtWidgets.QPushButton(self.groupSpeedZoom)
        self.btnSpeedByZoomOn.setObjectName("btnSpeedByZoomOn")
        self.layoutSpeedZoom.addWidget(self.btnSpeedByZoomOn)
        self.btnSpeedByZoomOff = QtWidgets.QPushButton(self.groupSpeedZoom)
        self.btnSpeedByZoomOff.setObjectName("btnSpeedByZoomOff")
        self.layoutSpeedZoom.addWidget(self.btnSpeedByZoomOff)
        self.editSpeedByZoomRatio = QtWidgets.QLineEdit(self.groupSpeedZoom)
        self.editSpeedByZoomRatio.setObjectName("editSpeedByZoomRatio")
        self.layoutSpeedZoom.addWidget(self.editSpeedByZoomRatio)
        self.layoutSpeedControl.addWidget(self.groupSpeedZoom)

        self.groupSpeedFly = QtWidgets.QGroupBox(self.groupSpeedControl)
        self.groupSpeedFly.setObjectName("groupSpeedFly")
        self.layoutSpeedFly = QtWidgets.QGridLayout(self.groupSpeedFly)
        self.layoutSpeedFly.setObjectName("layoutSpeedFly")
        self.btnGetCurrentSpeed = QtWidgets.QPushButton(self.groupSpeedFly)
        self.btnGetCurrentSpeed.setObjectName("btnGetCurrentSpeed")
        self.layoutSpeedFly.addWidget(self.btnGetCurrentSpeed, 0, 0, 1, 1)
        self.editCurrentSpeed = QtWidgets.QLineEdit(self.groupSpeedFly)
        self.editCurrentSpeed.setObjectName("editCurrentSpeed")
        self.editCurrentSpeed.setReadOnly(True)
        self.layoutSpeedFly.addWidget(self.editCurrentSpeed, 0, 1, 1, 1)
        self.btnSetTargetSpeed = QtWidgets.QPushButton(self.groupSpeedFly)
        self.btnSetTargetSpeed.setObjectName("btnSetTargetSpeed")
        self.layoutSpeedFly.addWidget(self.btnSetTargetSpeed, 1, 0, 1, 1)
        self.editTargetSpeed = QtWidgets.QLineEdit(self.groupSpeedFly)
        self.editTargetSpeed.setObjectName("editTargetSpeed")
        self.layoutSpeedFly.addWidget(self.editTargetSpeed, 1, 1, 1, 1)
        self.layoutSpeedControl.addWidget(self.groupSpeedFly)

        self.layoutMotorCtrl.addWidget(self.groupSpeedControl)

        # Acceleration group
        self.groupAcceleration = QtWidgets.QGroupBox(MainTab)
        self.groupAcceleration.setObjectName("groupAcceleration")
        self.layoutAcceleration = QtWidgets.QGridLayout(self.groupAcceleration)
        self.layoutAcceleration.setObjectName("layoutAcceleration")
        self.btnGetAcceleration = QtWidgets.QPushButton(self.groupAcceleration)
        self.btnGetAcceleration.setObjectName("btnGetAcceleration")
        self.layoutAcceleration.addWidget(self.btnGetAcceleration, 0, 0, 1, 1)
        self.btnSetAcceleration = QtWidgets.QPushButton(self.groupAcceleration)
        self.btnSetAcceleration.setObjectName("btnSetAcceleration")
        self.layoutAcceleration.addWidget(self.btnSetAcceleration, 0, 1, 1, 1)
        self.editAcceleration = QtWidgets.QLineEdit(self.groupAcceleration)
        self.editAcceleration.setObjectName("editAcceleration")
        self.layoutAcceleration.addWidget(self.editAcceleration, 0, 2, 1, 1)
        self.btnGetAccLevel = QtWidgets.QPushButton(self.groupAcceleration)
        self.btnGetAccLevel.setObjectName("btnGetAccLevel")
        self.layoutAcceleration.addWidget(self.btnGetAccLevel, 1, 0, 1, 1)
        self.btnSetAccLevel = QtWidgets.QPushButton(self.groupAcceleration)
        self.btnSetAccLevel.setObjectName("btnSetAccLevel")
        self.layoutAcceleration.addWidget(self.btnSetAccLevel, 1, 1, 1, 1)
        self.comboAccLevel = QtWidgets.QComboBox(self.groupAcceleration)
        self.comboAccLevel.setObjectName("comboAccLevel")
        self.comboAccLevel.addItems(["Sharp", "Standard", "Gentle"])
        self.layoutAcceleration.addWidget(self.comboAccLevel, 1, 2, 1, 1)

        self.layoutMotorCtrl.addWidget(self.groupAcceleration)

        # Position group
        self.groupPosition = QtWidgets.QGroupBox(MainTab)
        self.groupPosition.setObjectName("groupPosition")
        self.layoutPosition = QtWidgets.QGridLayout(self.groupPosition)
        self.layoutPosition.setObjectName("layoutPosition")
        self.btnGetPosition = QtWidgets.QPushButton(self.groupPosition)
        self.btnGetPosition.setObjectName("btnGetPosition")
        self.layoutPosition.addWidget(self.btnGetPosition, 0, 0, 1, 1)
        self.editMotorPosition = QtWidgets.QLineEdit(self.groupPosition)
        self.editMotorPosition.setObjectName("editMotorPosition")
        self.editMotorPosition.setReadOnly(True)
        self.layoutPosition.addWidget(self.editMotorPosition, 0, 1, 1, 1)
        self.btnABCount = QtWidgets.QPushButton(self.groupPosition)
        self.btnABCount.setObjectName("btnABCount")
        self.layoutPosition.addWidget(self.btnABCount, 0, 2, 1, 1)
        self.editABCount = QtWidgets.QLineEdit(self.groupPosition)
        self.editABCount.setObjectName("editABCount")
        self.editABCount.setReadOnly(True)
        self.layoutPosition.addWidget(self.editABCount, 0, 3, 1, 1)
        self.btnGetAngle = QtWidgets.QPushButton(self.groupPosition)
        self.btnGetAngle.setObjectName("btnGetAngle")
        self.layoutPosition.addWidget(self.btnGetAngle, 1, 0, 1, 1)
        self.editMotorAngle = QtWidgets.QLineEdit(self.groupPosition)
        self.editMotorAngle.setObjectName("editMotorAngle")
        self.editMotorAngle.setReadOnly(True)
        self.layoutPosition.addWidget(self.editMotorAngle, 1, 1, 1, 1)
        self.btnZCount = QtWidgets.QPushButton(self.groupPosition)
        self.btnZCount.setObjectName("btnZCount")
        self.layoutPosition.addWidget(self.btnZCount, 1, 2, 1, 1)
        self.editZCount = QtWidgets.QLineEdit(self.groupPosition)
        self.editZCount.setObjectName("editZCount")
        self.editZCount.setReadOnly(True)
        self.layoutPosition.addWidget(self.editZCount, 1, 3, 1, 1)

        self.layoutMotorCtrl.addWidget(self.groupPosition)

        # Zero-point Calibration group
        self.groupZeroCali = QtWidgets.QGroupBox(MainTab)
        self.groupZeroCali.setObjectName("groupZeroCali")
        self.layoutZeroCali = QtWidgets.QGridLayout(self.groupZeroCali)
        self.layoutZeroCali.setObjectName("layoutZeroCali")
        self.btnZeroCaliPlus = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnZeroCaliPlus.setObjectName("btnZeroCaliPlus")
        self.layoutZeroCali.addWidget(self.btnZeroCaliPlus, 0, 0, 1, 1)
        self.btnZeroCaliMinus = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnZeroCaliMinus.setObjectName("btnZeroCaliMinus")
        self.layoutZeroCali.addWidget(self.btnZeroCaliMinus, 0, 1, 1, 1)
        self.btnZeroCaliStatus = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnZeroCaliStatus.setObjectName("btnZeroCaliStatus")
        self.layoutZeroCali.addWidget(self.btnZeroCaliStatus, 0, 2, 1, 1)
        self.btnLockHome = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnLockHome.setObjectName("btnLockHome")
        self.layoutZeroCali.addWidget(self.btnLockHome, 0, 3, 1, 1)
        self.btnLockStatus = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnLockStatus.setObjectName("btnLockStatus")
        self.layoutZeroCali.addWidget(self.btnLockStatus, 0, 4, 1, 1)
        self.btnZeroHome = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnZeroHome.setObjectName("btnZeroHome")
        self.btnZeroHome.setFixedHeight(self.btnZeroHome.height() * 2)
        self.layoutZeroCali.addWidget(self.btnZeroHome, 0, 5, 2, 1)
        self.btnClearZeroCali = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnClearZeroCali.setObjectName("btnClearZeroCali")
        self.layoutZeroCali.addWidget(self.btnClearZeroCali, 1, 0, 1, 2)
        self.editZeroCali = QtWidgets.QLineEdit(self.groupZeroCali)
        self.editZeroCali.setObjectName("editZeroCali")
        self.editZeroCali.setReadOnly(True)
        self.editZeroCali.setAlignment(QtCore.Qt.AlignCenter)
        self.layoutZeroCali.addWidget(self.editZeroCali, 1, 2, 1, 1)
        self.btnUnlockHome = QtWidgets.QPushButton(self.groupZeroCali)
        self.btnUnlockHome.setObjectName("btnUnlockHome")
        self.layoutZeroCali.addWidget(self.btnUnlockHome, 1, 3, 1, 1)
        self.editLockStatus = QtWidgets.QLineEdit(self.groupZeroCali)
        self.editLockStatus.setObjectName("editLockStatus")
        self.editLockStatus.setReadOnly(True)
        self.editLockStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.layoutZeroCali.addWidget(self.editLockStatus, 1, 4, 1, 1)

        self.layoutMotorCtrl.addWidget(self.groupZeroCali)

        # Max Angle group
        self.groupMaxAngle = QtWidgets.QGroupBox(MainTab)
        self.groupMaxAngle.setObjectName("groupMaxAngle")
        self.layoutMaxAngle = QtWidgets.QHBoxLayout(self.groupMaxAngle)
        self.layoutMaxAngle.setObjectName("layoutMaxAngle")
        self.btnMaxAngleOn = QtWidgets.QPushButton(self.groupMaxAngle)
        self.btnMaxAngleOn.setObjectName("btnMaxAngleOn")
        self.layoutMaxAngle.addWidget(self.btnMaxAngleOn)
        self.btnMaxAngleOff = QtWidgets.QPushButton(self.groupMaxAngle)
        self.btnMaxAngleOff.setObjectName("btnMaxAngleOff")
        self.layoutMaxAngle.addWidget(self.btnMaxAngleOff)

        # Motor Type group
        self.groupMotorType = QtWidgets.QGroupBox(MainTab)
        self.groupMotorType.setObjectName("groupMotorType")
        self.layoutMotorType = QtWidgets.QHBoxLayout(self.groupMotorType)
        self.layoutMotorType.setObjectName("layoutMotorType")
        self.btnMotorType0p9d = QtWidgets.QPushButton(self.groupMotorType)
        self.btnMotorType0p9d.setObjectName("btnMotorType0p9d")
        self.layoutMotorType.addWidget(self.btnMotorType0p9d)
        self.btnMotorType1p8d = QtWidgets.QPushButton(self.groupMotorType)
        self.btnMotorType1p8d.setObjectName("btnMotorType1p8d")
        self.layoutMotorType.addWidget(self.btnMotorType1p8d)

        self.layoutMaxMotor = QtWidgets.QHBoxLayout()
        self.layoutMaxMotor.setObjectName("layoutMaxMotor")
        self.layoutMaxMotor.addWidget(self.groupMaxAngle)
        self.layoutMaxMotor.addWidget(self.groupMotorType)

        self.leftLayout.addWidget(self.groupPanTilt)
        self.leftLayout.addWidget(self.groupStall)
        self.leftLayout.addLayout(self.layoutMaxMotor)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.horizontalLayout.addLayout(self.layoutMotorCtrl)

        self.groupSpeedChart = QtWidgets.QGroupBox(MainTab)
        self.groupSpeedChart.setObjectName("groupSpeedChart")
        self.layoutSpeedChart = QtWidgets.QVBoxLayout(self.groupSpeedChart)
        self.layoutSpeedChart.setObjectName("layoutSpeedChart")
        self.chartSpeed = QtChart.QChartView(self.groupSpeedChart)
        self.chartSpeed.setObjectName("chartSpeed")
        self.layoutSpeedChart.addWidget(self.chartSpeed)
        self.layoutChartButtons = QtWidgets.QHBoxLayout()
        self.layoutChartButtons.setObjectName("layoutChartButtons")
        self.btnShowSpeed = QtWidgets.QPushButton(self.groupSpeedChart)
        self.btnShowSpeed.setObjectName("btnShowSpeed")
        self.layoutChartButtons.addWidget(self.btnShowSpeed)
        self.btnStopSpeed = QtWidgets.QPushButton(self.groupSpeedChart)
        self.btnStopSpeed.setObjectName("btnStopSpeed")
        self.layoutChartButtons.addWidget(self.btnStopSpeed)
        self.btnClearChart = QtWidgets.QPushButton(self.groupSpeedChart)
        self.btnClearChart.setObjectName("btnClearChart")
        self.layoutChartButtons.addWidget(self.btnClearChart)
        self.layoutSpeedChart.addLayout(self.layoutChartButtons)

        self.horizontalLayout.addWidget(self.groupSpeedChart)

        self.retranslateUi(MainTab)
        QtCore.QMetaObject.connectSlotsByName(MainTab)

    def retranslateUi(self, MainTab):
        _translate = QtCore.QCoreApplication.translate
        MainTab.setWindowTitle(_translate("MainTab", "MainTab"))
        self.groupPanTilt.setTitle(_translate("MainTab", "Pan/Tilt Control"))
        self.groupMove.setTitle(_translate("MainTab", "Continuous Move"))
        self.btnPanLeft.setText(_translate("MainTab", "Left"))
        self.btnPanStop.setText(_translate("MainTab", "Stop"))
        self.btnPanRight.setText(_translate("MainTab", "Right"))
        self.btnTiltUp.setText(_translate("MainTab", "Up"))
        self.btnTiltDown.setText(_translate("MainTab", "Down"))
        self.checkMoveStop.setText(_translate("MainTab", "Move+Stop"))
        self.btnStopAt.setText(_translate("MainTab", "Stop At"))

        self.groupAbsolute.setTitle(_translate("MainTab", "Absolute Move"))
        self.btnABS.setText(_translate("MainTab", "ABS"))
        self.btnABS2.setText(_translate("MainTab", "ABS2"))
        self.btnABSAngle.setText(_translate("MainTab", "Angle"))
        self.btnABSAngle2.setText(_translate("MainTab", "Angle2"))
        self.btnABSStop.setText(_translate("MainTab", "ABS Stop"))
        self.groupPanType.setTitle(_translate("MainTab", "Pan Direction"))
        self.btnPanType.setText(_translate("MainTab", "Get Pan Type"))
        self.btnABSAngleStop.setText(_translate("MainTab", "ABS Angle Stop"))

        self.groupRelative.setTitle(_translate("MainTab", "Relative Move"))
        self.btnRelUp.setText(_translate("MainTab", "Up"))
        self.btnRelLeft.setText(_translate("MainTab", "Left"))
        self.btnRelStop.setText(_translate("MainTab", "Stop"))
        self.btnRelRight.setText(_translate("MainTab", "Right"))
        self.btnRelDown.setText(_translate("MainTab", "Down"))
        self.labelRelStep.setText(_translate("MainTab", "Step"))

        self.groupStall.setTitle(_translate("MainTab", "Stall Calibration"))
        self.btnStallCaliOn.setText(_translate("MainTab", "On"))
        self.btnStallCaliOff.setText(_translate("MainTab", "Off"))

        self.groupSpeedControl.setTitle(_translate("MainTab", "Speed Control"))
        self.groupSpeedLevel.setTitle(_translate("MainTab", "Speed Lv. (1~127, default=100)"))
        self.labelSpeedLevel.setText(_translate("MainTab", "Level"))
        self.labelSpeedPPS.setText(_translate("MainTab", "PPS"))
        self.groupSpeedZoom.setTitle(_translate("MainTab", "Speed by Zoom Ratio"))
        self.btnGetSpeedByZoomRatio.setText(_translate("MainTab", "Get"))
        self.btnSpeedByZoomOn.setText(_translate("MainTab", "On"))
        self.btnSpeedByZoomOff.setText(_translate("MainTab", "Off"))
        self.groupSpeedFly.setTitle(_translate("MainTab", "Speed Change On The Fly"))
        self.btnGetCurrentSpeed.setText(_translate("MainTab", "Get Current Speed"))
        self.btnSetTargetSpeed.setText(_translate("MainTab", "Set Target Speed"))

        self.groupAcceleration.setTitle(_translate("MainTab", "Acceleration (pps/s, default=6016)"))
        self.btnGetAcceleration.setText(_translate("MainTab", "Get Value"))
        self.btnSetAcceleration.setText(_translate("MainTab", "Set Value"))
        self.btnGetAccLevel.setText(_translate("MainTab", "Get Level"))
        self.btnSetAccLevel.setText(_translate("MainTab", "Set Level"))

        self.groupPosition.setTitle(_translate("MainTab", "Position"))
        self.btnGetPosition.setText(_translate("MainTab", "Position"))
        self.btnABCount.setText(_translate("MainTab", "AB"))
        self.btnGetAngle.setText(_translate("MainTab", "Angle"))
        self.btnZCount.setText(_translate("MainTab", "Z"))

        self.groupZeroCali.setTitle(_translate("MainTab", "Zero-point Calibration"))
        self.btnZeroCaliPlus.setText(_translate("MainTab", "Cali+"))
        self.btnZeroCaliMinus.setText(_translate("MainTab", "Cali-"))
        self.btnZeroCaliStatus.setText(_translate("MainTab", "Cali. Status"))
        self.btnLockHome.setText(_translate("MainTab", "Lock Home"))
        self.btnLockStatus.setText(_translate("MainTab", "Lock Status"))
        self.btnZeroHome.setText(_translate("MainTab", "Home"))
        self.btnClearZeroCali.setText(_translate("MainTab", "Clear Cali."))
        self.btnUnlockHome.setText(_translate("MainTab", "Unlock Home"))

        self.groupMaxAngle.setTitle(_translate("MainTab", "Max Angle"))
        self.btnMaxAngleOn.setText(_translate("MainTab", "On"))
        self.btnMaxAngleOff.setText(_translate("MainTab", "Off"))

        self.groupMotorType.setTitle(_translate("MainTab", "Motor Type"))
        self.btnMotorType0p9d.setText(_translate("MainTab", "0.9X"))
        self.btnMotorType1p8d.setText(_translate("MainTab", "1.8X"))
        self.groupSpeedChart.setTitle(_translate("MainTab", "Speed Chart"))
        self.btnShowSpeed.setText(_translate("MainTab", "Start"))
        self.btnStopSpeed.setText(_translate("MainTab", "Stop"))
        self.btnClearChart.setText(_translate("MainTab", "Clear Chart"))
